**Converting Python list to NumPy array**

In [1]:
import numpy as np

lst=[1,2,3,4]
new_array=np.array(lst)

print(f"Original value is {lst} and it's type is {type(lst)}")
print(f"Original value is {new_array} and it's type is {type(new_array)}")


Original value is [1, 2, 3, 4] and it's type is <class 'list'>
Original value is [1 2 3 4] and it's type is <class 'numpy.ndarray'>


**.arange - Range of Numbers**  ---->   
*Syntax :- np.arange(start, stop, step)*

In [3]:
first10=np.arange(10)
first10natural=np.arange(1,10)
first10even=np.arange(0,10,2)

print(f"First 10 numbers:{first10}")
print("First 10 natural numbers:",first10natural)
print(f"Even numbers upto ten:{first10even}")


First 10 numbers:[0 1 2 3 4 5 6 7 8 9]
First 10 natural numbers: [1 2 3 4 5 6 7 8 9]
Even numbers upto ten:[0 2 4 6 8]


**np.zeroes**          --->        
*To create an array with Zeroes*

In [5]:
one_dzero=np.zeros(5)
two_dzero=np.zeros((2,5))

print(one_dzero)
print("------------")
print(two_dzero)

[0. 0. 0. 0. 0.]
------------
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


**np.ones**          --->        
*To create an array with Ones*

In [6]:
one_dones=np.ones(5)
two_dones=np.ones((2,5))

print(one_dones)
print("------------")
print(two_dones)

[1. 1. 1. 1. 1.]
------------
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


**.linspace() - Linear Space is function used to generate evenly spaced numbers over a specified range.**   ---->       
*Synatx:- np.linspace(start, stop, num=50) --> Here stop value also exists. And num is number of values (default=50)*


In [ ]:
arr = np.linspace(0, 10)
arr2=np.linspace(1,10,3)


print(arr)  # By default it gives 50 values
print("-----------")
print(arr2)

**eye() is a NumPy function used to create an identity matrix.**
*Syntax:- np.eye(N, M=None, k=0) N= number of rows, M=no. of columns, k=diagonal index*

In [11]:
arr = np.eye(3)
print(arr)

print("-----------")

arr = np.eye(4, k=1)    #upper diagonal
print(arr)

print("-----------")

arr = np.eye(4, k=-1)    #lower diagonal
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
-----------
[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]
-----------
[[0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


**np.random.rand() is a NumPy function used to generate random numbers between 0 and 1.**   --->       
*Random, Uniformly distributed, In the range [0, 1) (0 inclusive, 1 excluded)*

In [17]:
random_num=np.random.rand()
print(random_num)       #To print a Random Number

arr = np.random.rand(5)
print(arr)       #To print a 5 Random Numbers

mat=np.random.rand(2,3)
print(mat)

0.1738133402361428
[0.56045013 0.51404665 0.28587081 0.14419929 0.3866374 ]
[[0.06609225 0.86149857 0.28574797]
 [0.21645482 0.75438493 0.79751315]]


**.random.randn()   Generates random numbers from a standard normal distribution (mean = 0, std = 1)**  
*Random, Normal distributed (Range -inf to inf)(mean=0), In the range [0, 1) (0 inclusive, 1 excluded)*


In [18]:
np.random.randn()        # single value
np.random.randn(5)       # 1D array
np.random.randn(3, 4)    # 2D array


array([[ 0.33694422,  2.07548429,  1.28977278, -0.90639958],
       [-0.51213372,  0.61577921, -0.22191169,  0.41538557],
       [ 0.21371724,  0.21823893,  0.77307071,  0.78076915]])

**np.random.randint() -> Generates random integers within a specified range.**

In [ ]:
np.random.randint(10)           
np.random.randint(5, 15)        
np.random.randint(1, 10, 5)    
np.random.randint(1, 10, (3,2)) 

array([[4, 2],
       [3, 7],
       [8, 1]], dtype=int32)

**.seed()**     ---->           
Normally, random numbers change every time you run the code.
Using .seed() helps when you want consistent results (for testing, debugging, learning).

In [32]:
np.random.seed(5)
print(np.random.rand(1,3))

[[0.22199317 0.87073231 0.20671916]]


**.reshape(x,y)**       --->    
Used to give shape to an Array. If x*y != no.of elements then it gives error

In [35]:
arr=np.arange(12)
arr.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])